head: 
   favicon: "https://s1.ax1x.com/2023/08/19/pP3gBSx.md.png" #  the favicon
   high_res_favicon: "https://s1.ax1x.com/2023/08/19/pP3gBSx.png" #  the favicon using high quality format
   apple_touch_icon: "https://s1.ax1x.com/2023/08/19/pP3gBSx.png" # the iOS Home button icon
   keywords: "" #  the site keywords

uiux:
   android_chrome_color: "#eeeeee" #  the color of the Chrome address bar
   nprogress_color: "#29d" #  the color of the top loading progress bar
   nprogress_buffer: 200 # the top loading progress bar buffers
   meng: false

background: 
   purecolor: "#eeeeee" # the background color

img: 
   avatar: "https://s1.ax1x.com/2023/08/19/pP3gBSx.png" # your avatar

card: 
   card_shadow: 1 # card shadow (0-24), 0 is not displayed
   card_hoverable: false # When the hover to deepen the shadow

many_authors: false

sns_share: # SNS Share Switch
   twitter: true
   facebook: false
   googleplus: false
   weibo: true
   linkedin: false
   qq: true
   telegram: true

comment:
  used: "" # disqus,livere,gitment,valine
  # disqus config
  disqus_shortname: "" # Your disqus 
  disqus_button: true # disqus load button
  disqus_proxy: false # # disqus proxy(Do not use)
  disqus_proxy_url: "" # (Do not use)
  disqus_api_key: "" # (Do not use)
  # livere config
  livere_type: 'city'
  livere_data_uid: ''
  # gitment config
  owner: ""
  repo: ""
  client_id: ""
  client_secret: ""
  #valine config
  valine_app_id: ''
  valine_app_key: ''
  valine_placeholder: "ヾﾉ≧∀≦)o来啊，快活啊!"

prism:
  themes: prism-okaidia
  components: 
    - bash 
  plugins: 

google_analytics: "G-KC7CSDP362"  # google analytics code

lang: "zh-CN"  # lang

deploy: "" # if you used coding pages

custom_css: "customCss.css" # Use the assets/css/customCss.css

custom_js: "" # Use the assets/js/customJS.js